version: "3.9"

services:
  backend:
    build: ./todo-backend
    container_name: todo-backend
    env_file:
      - ./todo-backend/.env
    expose:
      - "5000"
    networks:
      - todo-net

  frontend:
    build: ./todo-frontend
    container_name: todo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge
