version: "3.9"

services:
  backend:
    build: ./todo-backend
    container_name: todo-backend
    # Added env in jenkins credentials
    # env_file:
    #   - ./todo-backend/.env
    expose:
      - "5000"
    networks:
      - todo-net
    restart: unless-stopped

  frontend:
    build: 
      context: ./todo-frontend
      args:
        REACT_APP_API_URL : /api   
    container_name: todo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - todo-net
    restart: unless-stopped

networks:
  todo-net:
    driver: bridge
